let x = exception(TypeError, "new exception");
print x;